---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "marketing-service"
  namespace: "default"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    app: "marketing"
  type: "NodePort"
