# This file configures the hello-world app which serves public web traffic.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discounts
  template:
    metadata:
      labels:
        app: discounts
    spec:
      containers:
      - name: discounts-app
        # Replace workflows-demo-314019 with your project ID
        # gcloud builds submit --tag gcr.io/workflows-demo-314019/discounts .
        # gcloud container clusters create workflow-demo --num-nodes 2 --zone us-east1-b
        image: gcr.io/workflows-demo-314019/discounts:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
          - name: PORT
            value: "8080"